#name: Run scheduled action
#on:
#  schedule:
#    # You need to set your schedule here
#    - cron: "* * * * *"

#jobs:
#  pull_data:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          persist-credentials: false
#          fetch-depth: 0

#     - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"

#      - name: Install dependencies
#        run: pip install -r requirements.txt

#      - name: Pull data
#        run: python3 main.py
#        env:
#          API_KEY: ${{ secrets.API_KEY }}

#      # NOTE: This commits everything in the `data` directory. Make sure this matches your needs
#      - name: Git commit
#        run: |
#          git add data
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git commit -m "Commiting data"

#     # NOTE: Check that your branch name is correct here
#      - name: Git push
#        run: |
#          git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
#        env:
#          TOKEN: ${{ secrets.GITHUB_TOKEN }}
